# This Compose file is just for development. It's NOT intended for production use

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.1
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      # - "8080:8080"
  server:
    container_name: tix-q-server
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - "latest"
    networks:
      - cockroachdb
    depends_on:
      - cockroachdb
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://root@cockroachdb:26257/defaultdb?schema=public&sslmode=disable
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  cockroach-data:
    name: cockroach-data
networks:
  cockroachdb:
    name: cockroachdb
